-- Database: tadsfit

-- DROP DATABASE IF EXISTS tadsfit;

CREATE DATABASE tadsfit
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aluno
(
    nome text COLLATE pg_catalog."default",
    matricula integer NOT NULL,
    id_filial integer,
    id_fun integer,
    idade integer,
    peso double precision,
    altura double precision,
    sexo text COLLATE pg_catalog."default",
    contato text COLLATE pg_catalog."default",
    endereco text COLLATE pg_catalog."default",
    CONSTRAINT aluno_pkey PRIMARY KEY (matricula)
);

CREATE TABLE IF NOT EXISTS public.equipamentos
(
    patrimonio integer NOT NULL,
    id_filial integer,
    nome text COLLATE pg_catalog."default",
    status1 text COLLATE pg_catalog."default",
    CONSTRAINT equipamentos_pkey PRIMARY KEY (patrimonio)
);

CREATE TABLE IF NOT EXISTS public.filial
(
    idf integer NOT NULL,
    endereco text COLLATE pg_catalog."default",
    contato text COLLATE pg_catalog."default",
    horario text COLLATE pg_catalog."default",
    CONSTRAINT filial_pkey PRIMARY KEY (idf)
);

CREATE TABLE IF NOT EXISTS public.funcionarios
(
    matricula integer NOT NULL,
    id_filial integer,
    nome text COLLATE pg_catalog."default",
    idade integer,
    sexo text COLLATE pg_catalog."default",
    contato text COLLATE pg_catalog."default",
    horario text COLLATE pg_catalog."default",
    endereco text COLLATE pg_catalog."default",
    CONSTRAINT funcionarios_pkey PRIMARY KEY (matricula)
);

ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT aluno_id_filial_fkey FOREIGN KEY (id_filial)
    REFERENCES public.filial (idf) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT aluno_id_fun_fkey FOREIGN KEY (id_fun)
    REFERENCES public.funcionarios (matricula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.equipamentos
    ADD CONSTRAINT equipamentos_id_filial_fkey FOREIGN KEY (id_filial)
    REFERENCES public.filial (idf) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.funcionarios
    ADD CONSTRAINT funcionarios_id_filial_fkey FOREIGN KEY (id_filial)
    REFERENCES public.filial (idf) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;